### PR TITLE
Enable keybord navigation for the search box.

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by jmigual** [comment]
Hi thanks for your work! I like the new icon it's kind of more descriptive.

Some issues:
- Only the library can be seen in the left pane. It can also be seen that the selected pane bar is only half visible.

image

- The library can be activated in all panes but the library table is only shown in the first pane
- Sometimes when preselecting a pane it needs a double click and sometimes it only needs one click. 

By the way I'll be working in the query editor which is nearly finished. :wink:

**Comment by daschuer** [comment]
Yes, It looks like, I have messed things up a bit. 

Currently I am working on Tab and Shift+Tab cycling nicely though the 
ButtonBar -> LibrarySidebar -> Pane1 -> Pane2 
It is hard to track what is relay happen, but I am still in a good mood.
This should be finished first.

**Comment by jmigual** [comment]
Ok, fine :wink:

**Comment by daschuer** [comment]
Now the first step is done, keyboard navigation works "normal" again. 
* Cycling though the widget using TAB
* Navigating in the Table/Tree using cursor keys
* Enter = Select 
* I have also enabled Del Ctrl+C Ctrl+V Ctrl+X
* Crtl+F Search

The keys consumed by the widget are not mappable anymore. This grantees that we can always control the library like all other apps.   

The next step is to map the library control keys to midi. 
I think we have to do some more automatic actions to have fully control over the Library with less keys. 

If you can effort the time, I would be happy about a review and test. Thank you.

**Comment by jmigual** [comment]
Sorry for not answering sooner and thank you for your work, the navigation feels so natural now, also the Ctrl+C, Ctrl+V and Ctrl+X have many potential i like it.

> The next step is to map the library control keys to midi. 
I think we have to do some more automatic actions to have fully control over the Library with less keys.

What do you mean? Are you referring to the control objects related to the library that were going to be added?

**Comment by daschuer** [comment]
Yes, somehow. Our original idea was to map the midi controls one to one to a keyboard key. 
Currently this will hardly work, because we have now a lot of dedicated keyboard keys, but only a view midi keys in most cases.   For example are left/right keys used to scroll inside the grid. It would be a waste to use the left/right midi keys just for that. 

I am also wondering which actions are really necessary on the controller. Since once the user wants to search for a track, he has to use the keyboard anyway.  Do we need to consider a Keyboard less setup?

**Comment by jmigual** [comment]
For me it seems that there are few actions to do:
- Change widget
- Select item/track
- Navigate through items/tracks

This actions should be able to be done with any controller. Also there are controllers which have the "load to deck X" button that can be mapped directly. 
I think that this with this behavior mapping the midi keys to keyboard keys should be an easy task and many of the existing code can be reused because it will only imply changing the Control Objects mapping:
- `SelectNextTrack` -> Move selection one item down
- `SelectPrevTrack` -> Move selection one item up
- `SelectTrackKnob` -> Move selection with knob
- `Select*Playlist` -> Same as `Select*Track` or remove the Control Object since this is no longer necessary
- **new** `SelectItem` -> Same behavior as enter key 
- `ToggleSelectedSidebarItem` -> There's no need for this since it can be done with `SelectItem`

**Pull request merged**
